### ISSUE TITLE
Deprecate Homebrew::Hooks

### ISSUE THREAD

**Issue by MikeMcQuaid** [boxen/puppet-homebrew#105]
It would be nice to be able to deprecate Homebrew::Hooks::Bottles and have Boxen use Homebrew's native bottles at this stage.

Thoughts?

**Comment by jacobbednarz** [comment]
From previous chats with Boxen maintainers, this was from back in the days when Homebrew wasn't as reliable as present day and a bunch of things were being done to verify integrity and increase reliability. I'm not fully across what else is in the S3 bucket so would you be able to take a look in there? Or see if another Hubber could print out a recursive listing of it? Happy if you wanna drop me an email and we can discuss anything of interest you find in there.

In general, 👍  let's do this.

**Comment by dgoodlad** [comment]
I'm :+1: on this idea too. The original intent of the bottle hooks were to ensure consistency when homebrew was in flux, especially given many boxen-provided homebrew packages had custom formulae.

IMO if an org wants stable package versions, they should probably maintain their own homebrew tap, and associated bottles there, rather than using this shimmed-in boxen-specific method.

@jacobbednarz specifically regarding your worries about the S3 bucket, I don't think that we need to audit what's there in order to move to using homebrew's native bottles. It'd definitely be worth having a dig around in there at some point, but shouldn't be a blocker to this move.

**Comment by MikeMcQuaid** [comment]
> and a bunch of things were being done to verify integrity and increase reliability.

I know you weren't stating this but just to it doesn't go unchallenged: the Boxen method doesn't verify checksums so it significantly less secure than Homebrew's (albeit easier).

> I'm not fully across what else is in the S3 bucket so would you be able to take a look in there? Or see if another Hubber could print out a recursive listing of it? Happy if you wanna drop me an email and we can discuss anything of interest you find in there.

I can do this if needed but as @dgoodlad mentioned, I'm not sure it's needed. 

> IMO if an org wants stable package versions, they should probably maintain their own homebrew tap, and associated bottles there, rather than using this shimmed-in boxen-specific method.

👍 particularly given Homebrew now supports versioned formulae in the main tap, too.

**Comment by jacobbednarz** [comment]
> I can do this if needed but as @dgoodlad mentioned, I'm not sure it's needed.

It's definitely not a have to but I'd rather be confident that we knew what was in there instead of guessing down the track if the question arises.

As far as I can see, this should be as straight forward as [boxen-bottle-hooks.rb](https://github.com/boxen/puppet-homebrew/blob/master/files/boxen-bottle-hooks.rb) and it should Just Work™. I'm happy to open a PR (unless you'd like to @MikeMcQuaid?) and run this internally for a bit to confirm everything behaves itself.

**Comment by MikeMcQuaid** [comment]
> It's definitely not a have to but I'd rather be confident that we knew what was in there instead of guessing down the track if the question arises.

> As far as I can see, this should be as straight forward as boxen-bottle-hooks.rb and it should Just Work™. I'm happy to open a PR (unless you'd like to @MikeMcQuaid?) and run this internally for a bit to confirm everything behaves itself.

Pretty much, yeh. After that the custom-uploaded Boxen binary packages/bottles will no longer work on future releases of Boxen and when you're comfortable we can eventually consider removing that from Homebrew too and then it will stop working for previous releases also.

**Comment by jacobbednarz** [comment]
@MikeMcQuaid kicking this off in #105. I'll let this bake internally for a bit before we merge.

**Comment by MikeMcQuaid** [comment]
Thanks @jacobbednarz! Will remove these hooks in next stable release.

**Comment by jacobbednarz** [comment]
i've released this via [2.2.0](https://github.com/boxen/puppet-homebrew/releases/tag/2.2.0) and will update upstream `boxen/our-boxen` with the changes once this has settled for a week or so.

**Comment by MikeMcQuaid** [comment]
> i've released this via 2.2.0 and will update upstream boxen/our-boxen with the changes once this has settled for a week or so.

@jacobbednarz Thanks for that! I plan on landing Homebrew 1.4.0 on Mondayish next week with https://github.com/Homebrew/brew/pull/3510 so it would be cool if upstream `boxen/our-boxen` was carrying 2.2.0 before that.

**Comment by jacobbednarz** [comment]
Done! Will merge boxen/our-boxen#858 when CI is finished
