### ISSUE TITLE
gcc48 brew calling Formula.sha1

### ISSUE THREAD

**Issue by dkowis** [boxen/puppet-homebrew#98]
```
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/gcc48.rb:27:in `<class:Gcc48>'
Please report this to the boxen/brews tap!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  boxen/brews
```

I saw a related issue #96, but it doesn't seem like all of them were covered. Apparently I have gcc48 installed, and so brew doctor is mad about it. Thanks!

**Comment by pelegb** [comment]
+1

**Comment by jacobbednarz** [comment]
Thanks for the report! I'm happy to accept a PR for this against [`boxen/puppet-gcc`](https://github.com/boxen/puppet-gcc) if either of you would like to take a crack at it.

**Comment by pelegb** [comment]
@jacobbednarz  If I understand correctly this is already fixed. You only need to create a new release.

**Comment by jacobbednarz** [comment]
@pelegb errm, kind of? [`boxen/puppet-gcc`](https://github.com/boxen/puppet-gcc) now only ships with gcc5 since boxen/puppet-gcc#16. gcc4* should no longer be a thing.

I'm not sure about needing a new release since 3.0.2 from the [releases](https://github.com/boxen/puppet-gcc/releases) seems to be matching master in that repository. [`boxen/our-boxen`](https://github.com/boxen/our-boxen/blob/master/Puppetfile#L44) has this at the latest version too.

Are you just missing these updates from your forks?

**Comment by eugeneius** [comment]
I ran into this problem too, and I'm using the latest version of the `puppet-gcc` module.

I manually uninstalled the offending packages as a workaround:

```bash
brew uninstall apple-gcc42 gcc48
```

Even though they're no longer installed since https://github.com/boxen/puppet-gcc/pull/16, those other gcc packages will still be present on any machine that ever ran Boxen with a previous version of the module. We should probably uninstall them automatically if they're present.

**Comment by jacobbednarz** [comment]
perhaps we can open a PR with the following instead?

```puppet
package { ['apple-gcc42', 'gcc48']:
  ensure => absent
}
```

**Comment by eugeneius** [comment]
Yeah sorry, that's what I meant by "uninstall them automatically" - not shelling out to run the `brew` command 😬 

@dkowis @pelegb do either of you want to try fixing the module with that approach? ☝️

**Comment by dkowis** [comment]
I'll do it.

**Comment by jacobbednarz** [comment]
Awesome, I'll close this one off and we'll discuss the change in the correct repository. 

Thanks everyone!
